
name: CI/CD for Dockerized Flask App

# On which events to trigger
on:
  push:
    # On which branches
    branches: [ main ]
  pull-request:
    branches: [ main ]

jobs: 
  # Unit testing job name
  build-and-test: 
    # Container
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Version of Python to run within container
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Runs all files and functions starting with test_
    - name: Run tests
      run: |
        pytest

  # Pushing docker image to dockerhub
  build-and-push:
    needs: build-and-test
    runs-on: ubuntu latest

    # Checkout repo, login to docker, build and push
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flasktest-app:latest

      - name: Image digest
        run: echo $ {{ steps.build-and-push.outputs.digest }}

