name: CI/CD for Dockerized Flask App

# On which events to trigger
on:
  push:
    # On which branches
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  # Build and test the Docker container
  docker-build-and-test: 
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the docker image
      run: docker build . --file Dockerfile --tag workflow:test

    - name: Run Docker container
      run: docker run -d -p 5000:5000 --name test_container workflow:test

    # TODO Replace curl with app's expected endpoint
    - name: Test the running container
      run: |
        sleep 5
        curl -f http://localhost:5000 

    - name: Stop running container
      run: docker stop test_container


  # Unit testing job
  unit-test: 
    # Container
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Version of Python to run within container
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Runs all files and functions starting with test_
    - name: Run tests
      run: |
        pytest

  # Pushing docker image to dockerhub
  build-and-push:
    needs: docker-build-and-test
    runs-on: ubuntu-latest

    # Checkout repo, login to docker, build and push
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        id: build_and_push 
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hcerc-project:latest

      # - name: Output image digest
      #   run: echo "Image Digest: ${{ steps.build_and_push.outputs.digest }}"